SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
ON C.CAR_ID = RH.CAR_ID
WHERE C.CAR_TYPE LIKE '세단' AND DATE_FORMAT(RH.START_DATE, '%Y-%m') = '2022-10'
ORDER BY C.CAR_ID DESC
