-- 기본적인 ON 절 사용
SELECT COUNT(FI.FISH_TYPE) FISH_COUNT, FNI.FISH_NAME
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
GROUP BY FNI.FISH_TYPE, FNI.FISH_NAME
ORDER BY FISH_COUNT DESC

-- NATURAL JOIN (자연조인)
SELECT COUNT(FI.FISH_TYPE) FISH_COUNT, FNI.FISH_NAME
FROM FISH_INFO FI
NATURAL JOIN FISH_NAME_INFO FNI 
GROUP BY FNI.FISH_TYPE, FNI.FISH_NAME
ORDER BY FISH_COUNT DESC*/

-- USING 절 사용
SELECT COUNT(FI.FISH_TYPE) FISH_COUNT, FNI.FISH_NAME
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI USING(FISH_TYPE)
GROUP BY FNI.FISH_TYPE, FNI.FISH_NAME
ORDER BY FISH_COUNT DESC
