SELECT CII.ITEM_ID, CII.ITEM_NAME, CII.RARITY
FROM ITEM_INFO PII
INNER JOIN ITEM_TREE IT ON(IT.PARENT_ITEM_ID = PII.ITEM_ID)
INNER JOIN ITEM_INFO CII ON(CII.ITEM_ID = IT.ITEM_ID)
WHERE PII.RARITY = 'RARE'
ORDER BY CII.ITEM_ID DESC
