SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES S ON (S.NAME IN ('C#', 'Python') 
                      AND D.SKILL_CODE & S.CODE)
ORDER BY D.ID

-- 중복처리에 유의
