SELECT E2.YEAR, E2.MAX_SIZE_OF_COLONY  - E1.SIZE_OF_COLONY AS YEAR_DEV, E1.ID
FROM ECOLI_DATA E1
INNER JOIN (SELECT YEAR(ET.DIFFERENTIATION_DATE) AS YEAR, MAX(ET.SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
             FROM ECOLI_DATA ET
             GROUP BY YEAR) E2 ON (E2.YEAR = YEAR(E1.DIFFERENTIATION_DATE))
ORDER BY E2.YEAR, YEAR_DEV

-- ORDER BY 절에서 SELECT 절의 별칭을 사용할 수 있지만, 테이블 별칭을 붙이면 Unknown column 오류 발생
-- ex) ORDER BY E1.YEAR_DEV
